### ISSUE TITLE
Implement Crafting System

### ISSUE THREAD

**Issue by cmcintosh** [WembassyCo/PixalSurvival#10]
Implement the core of the crafting system, create around 10 recipes for testing the functionality of the system.

- [ ] Create 10 recipes for the crafting system
- [ ] Create 1 consumable items, that can be created by the crafting system (Throwable Snowballs, Exploding Snowballs)
- [ ] Create 1 item that can be equipped for each slot.
- [ ] Create 1 melee weapon
