### ISSUE TITLE
Implement Vendor(s) NPC system

### ISSUE THREAD

**Issue by cmcintosh** [WembassyCo/PixalSurvival#12]
Implement the core functionality for Vendor npcs to allow dialog, and trading with them.

- [ ] Extend Trading system for NPC Vendors
- [ ] Extend Inventory system for NPC Vendors
- [ ] Implement some sort of Inflation / Variable market.
