### ISSUE TITLE
Implement Player Character Persistence

### ISSUE THREAD

**Issue by cmcintosh** [WembassyCo/PixalSurvival#14]
We need to keep track of various player data for the game. This should be stored / retrieved from the Drupal database.

- [ ] Track user's character name
- [ ] Track user's character data
- [ ] Track user's character location/etc
- [ ] Allow users to teleport to private **Region**
