### ISSUE TITLE
Regions

### ISSUE THREAD

**Issue by cmcintosh** [WembassyCo/PixalSurvival#16]
Regions are sections of the game, that can be created and managed by players in game.  
Some example regions:
 - Social region for a NFT collection where holders can join, talk, and interact.
 - Private region owned by a single player that can build / customize the area.
 - A shared adventure/survival region that allows for typical RPG / MMO / Survival style play

The First version of this will be used to create the following three region types:
- Personal Island for Metapenguin Island tokens, each player that connects and has a MPI NFT token will have a personal region that they can customize, ie placing buildable structures.
- Social / Shared MPI island, this island will be the initial spawn-in region for new players, and will be a non-combat area
- Survival Island - This island will be a survival RPG style game, similar to Rust/Ark where players will be able to explore, complete missions, and place structures.

Create and implement the base system in Database, and for the game to allow for the creation, management, and customization of regions.

The initial setup should be around the following:
- [ ] Region Name / Description / Ownership
- [ ] Region Allowed/Blocked content lists.
- [ ] Region customizations (Placement of buildings)
- [ ] Private / Public access of region from players
- [ ] In game UI for managing the region
- [ ] In game UI for creation of the region
