### ISSUE TITLE
Implement a Friends List system

### ISSUE THREAD

**Issue by cmcintosh** [WembassyCo/PixalSurvival#6]
Implement a friends system that allows for the core functionality of interacting with other players.

- [ ] View current friends
- [ ] Send Friend Invites
- [ ] Remove Friends
- [ ] Friend Online notifications
